---
version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: daily
      # UTC time
      time: "09:42"
    rebase-strategy: disabled
    commit-message:
      prefix: "A0-3951: "
    groups:
      all-rust-deps-except-liminal:
        patterns:
          - "*"
        exclude-patterns:
          - "baby-liminal-extension*"
          - "pallets/vk-storage*"
      liminal-deps:
        patterns:
          - "baby-liminal-extension*"
          - "pallets/vk-storage*"
    pull-request-branch-name:
      separator: "-"
    ignore:
      - dependency-name: "aleph-bft"
      - dependency-name: "aleph-bft-rmc"
      - dependency-name: "aleph-bft-types"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: sunday
      # UTC time
      time: "06:15"
    rebase-strategy: disabled
    commit-message:
      prefix: "A0-3952: "
    groups:
      all-github-actions:
        patterns:
          - "*"
    pull-request-branch-name:
      separator: "-"
    reviewers:
      - "Marcin-Radecki"
      - "Mikolaj Gasior"

