---
name: Compare docker image digests
description:
  This action compares whether two docker images have the same digests
inputs:
  docker-image-a:
    required: true
    description: Public URL of an image A to check
  docker-image-b:
    required: true
    description: Public URL of an image B to check

runs:
  using: composite
  steps:
    - name: Install jq
      shell: bash
      run: |
        sudo apt-get install -y jq

    - name: Check RC image existence in ECR
      shell: bash
      run: |
        digest_a=$(docker manifest inspect ${{ inputs.docker-image-a }} -v | \
          jq -r '.Descriptor.digest')
        digest_b=$(docker manifest inspect ${{ inputs.docker-image-b }} -v | \
          jq -r '.Descriptor.digest')
        if [[ "${digest_a}" != "${digest_b}" ]]; then
          echo "Error: docker image ${{ inputs.docker-image-a }} has different digest"
          echo "${digest_a} than docker image ${{ inputs.docker-image-b }} that has digest"
          echo "${digest_b}"
          exit 1
        fi
