---
name: Get ref git properties
description:
  Returns basic git ref properties for the commit it runs on, such as tag, branch or commit SHA.
  This actions is intended to be triggerd either via pull request, tag push or direct push to
  a release branch.

outputs:
  branch:
    description: Branch name
    value: ${{ steps.branch.outputs.name }}
  branch_name_flattened:
    description: Branch name with / (slash) replaced with - (hyphen)
    value: ${{ steps.branch.outputs.name_flattened }}
  tag:
    description: Tag name
    value: ${{ steps.tag.outputs.name }}
  sha:
    description: Unique commit SHA
    value: ${{ steps.commit.outputs.sha }}

runs:
  using: composite
  steps:
    - name: Get tag properties
      id: tag
      if: startsWith(github.ref, 'refs/tags/')
      shell: bash
      env:
        HEAD_REF: ${{ github.ref }}
      run: |
        echo name=$(echo ${HEAD_REF#refs/tags/}) >> $GITHUB_OUTPUT

    - name: Get branch properties
      id: branch
      if: startsWith(github.ref, 'refs/pull/')
      shell: bash
      env:
        HEAD_REF: ${{ github.head_ref }}
      run: |
        echo name=$(echo ${HEAD_REF#refs/heads/})
        echo name_flattened=$(echo ${HEAD_REF#refs/heads/} | tr / -)
        echo sha_short=$(git rev-parse --short HEAD)
