---
name: Deploy to Mainnet

on:
  release:
    types: [released]

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}

jobs:
  deploy-mainnet:
    name: Deploy new aleph-node image to Mainnet EKS
    runs-on: ubuntu-20.04
    environment: 'mainnet'
    env:
      AWS_REGION: us-east-1  # this region is used by all public ECR repos
    steps:
      - name: GIT | Checkout
        uses: actions/checkout@v3

      - name: Call action get-ref-properties
        id: get-ref-properties
        uses: ./.github/actions/get-ref-properties

      - name: Test get-ref-properties
        shell: bash
        run: |
          echo "branch = ${{ steps.get-ref-properties.outputs.branch }}"
          echo "sha = ${{ steps.get-ref-properties.outputs.sha }}"

