---
name: Deploy to Testnet

on:
  workflow_call:

# there might be only one deployment to the Testnet at a time
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  check-vars-and-secrets:
    name: Check vars and secrets
    uses: ./.github/workflows/_check-vars-and-secrets.yml
    secrets: inherit

  deploy-to-testnet:
    needs: [check-vars-and-secrets]
    name: Deploy new aleph-node image to Testnet EKS
    uses: .github/actions/update-node-image-infra
    with:
      env: testnet
    secrets: inherit

  push-dockerhub-image-testnet:
    needs: [deploy-to-testnet]
    runs-on: ubuntu-20.04
    steps:
      - name: Get docker image names
        id: get-docker-image-names
        uses: ./.github/actions/get-docker-image-names
        with:
          ecr-registry: ${{ vars.ECR_PUBLIC_REGISTRY }}

      - name: Build and push Docker Hub image for Testnet
        uses: ./.github/actions/build-and-push-dockerhub-image
        with:
          source-image: ${{ steps.get-docker-image-names.outputs.ecr-deploy-image }}
          target-image: ${{ steps.get-docker-image-names.outputs.dockerhub-testnet-image }}
          additional-image:
            ${{ steps.get-docker-image-names.outputs.dockerhub-testnet-latest-image }}
          dockerhub-username: "${{ secrets.DOCKERHUB_USERNAME }}"
          dockerhub-password: "${{ secrets.DOCKERHUB_PASSWORD }}"
          push: 'true'

  slack:
    name: Slack notification
    runs-on: ubuntu-20.04
    needs: [push-dockerhub-image-testnet]
    if: always()
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Send Slack message
        uses: ./.github/actions/slack-notification
        with:
          notify-on: "always"
        env:
          # TODO change it in next PR to SLACK_WEBHOOK_DEV_ONDUTY
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_TEMP_GRAFANA_NOTIFICATIONS }}
