---
name: Deploy to Testnet

on:
  release:
    types: [prereleased]

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}

jobs:
  deploy-testnet:
    name: Deploy new aleph-node image to Testnet EKS
    runs-on: ubuntu-20.04
    environment:
      name: testnet
    env:
      AWS_REGION: us-east-1  # this region is used by all public ECR repos
    steps:
      - name: GIT | Checkout
        uses: actions/checkout@v3

      - name: Call action get-ref-properties
        id: get-ref-properties
        uses: ./.github/actions/get-ref-properties

      - name: Test get-ref-properties
        shell: bash
        run: |
          echo "tag = ${{ steps.get-ref-properties.outputs.tag }}"
          echo "sha = ${{ steps.get-ref-properties.outputs.sha }}"


