---
name: Push release candidate image of aleph-node to ECR and DockerHub

on:
  push:
    tags:
      - 'r-*'

jobs:
  check-vars-and-secrets:
    name: Check vars and secrets
    uses: ./.github/workflows/_check-vars-and-secrets.yml
    secrets: inherit

  push-ecr-image:
    needs: [check-vars-and-secrets]
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Call action get-ref-properties
        id: get-ref-properties
        uses: ./.github/actions/get-ref-properties

      - name: Get node image names
        id: get-node-image-names
        shell: bash
        run: |
          commit_sha=${{ steps.get-ref-properties.outputs.sha }}
          commit_tag=${{ steps.get-ref-properties.outputs.tag }}
          ecr=${{ vars.ECR_PUBLIC_REGISTRY }}
          echo "rc-image=${ecr}aleph-node:${commit_sha}" >> $GITHUB_OUTPUT
          echo "deploy-image=${ecr}aleph-node:${commit_sha}" >> $GITHUB_OUTPUT

      # if r-* tag was pushed on a commit that is not on main or release branch, below step would
      # fail, as there would be no aleph-node-<sha> image on ECR for <sha> that is not on main
      # or release branch
      - name: Check RC image existence in ECR
        shell: bash
        run: |
          rc_image=${{ steps.get-node-image-names.outputs.rc-image }}
          image_not_exist=$(docker manifest inspect $rc_image &> /dev/null ; echo $?)
          if [[ $image_not_exist -eq 1 ]]; then
            echo "::error title=Wrong docker image tag::Docker image ${rc_image} doesn't exist"
            echo "You might have tagged not release or main branch, or after merge to main"
            echo "workflow have not finished yet."
            exit 1
          fi

      - name: Login to Public Amazon ECR
        id: login-public-ecr
        uses: docker/login-action@v2
        with:
          registry: ${{ vars.ECR_PUBLIC_HOST }}
          username: ${{ secrets.AWS_MAINNET_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_MAINNET_SECRET_ACCESS_KEY }}

      - name: Tag and push image to ECR
        shell: bash
        run: |
          rc_image=${{ steps.get-node-image-names.outputs.rc-image }}
          deploy_image=${{ steps.get-node-image-names.outputs.deploy-image }}

          docker pull ${rc_image}
          docker tag ${rc_image} ${deploy_image}
          docker push ${deploy_image}

  slack:
    name: Slack notification
    runs-on: ubuntu-20.04
    needs: [push-ecr-image]
    if: always()
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Send Slack message
        uses: ./.github/actions/slack-notification
        with:
          notify-on: "failure"
        env:
          # TODO change it in next PR to SLACK_WEBHOOK_DEV_ONDUTY
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_TEMP_GRAFANA_NOTIFICATIONS }}
